main-jar=frostguard-watcher-${project.version}.jar
main-class=dev.frostguard.watcher.TelegramWatcher
description=Frostguard Telegram Watcher
java-options=--enable-native-access=ALL-UNNAMED -Dfrostguard.channel=${frostguard.release.channel} -Dfrostguard.application.id=${frostguard.product.identifier} -Dfrostguard.update.pullRequestBuild=${frostguard.pull-request-build} "-Duser.dir=$APPDIR" "-Dfrostguard.launcher=$APPDIR/../${frostguard.product.name}.exe" "-Dfrostguard.watcher.launcher=$APPDIR/../${frostguard.watcher.name}.exe"
win-menu=false
win-shortcut=false
